create table if not exists public.orarend_verziok (
    id           bigint generated by default as identity primary key,

    nev          text not null,
    tanev        text not null,
    megjegyzes   text null,

    statusz      text not null default 'draft'
                 check (statusz in ('draft', 'active', 'archived')),

    letrehozta   uuid null,
    created_at   timestamptz not null default now(),
    published_at timestamptz null
);

-- Egy időben legfeljebb EGY aktív órarend lehet. Ezt adatbázis szinten
-- kényszerítjük ki, hogy programhiba se tudjon két aktív verziót előállítani.
create unique index if not exists orarend_verziok_egy_aktiv
    on public.orarend_verziok (statusz)
    where statusz = 'active';

create index if not exists orarend_verziok_statusz_idx
    on public.orarend_verziok (statusz, created_at desc);

-- ─────────────────────────────────────────────────────────────────
-- 2. Import napló
-- ─────────────────────────────────────────────────────────────────

create table if not exists public.importok (
    id               bigint generated by default as identity primary key,

    verzio_id        bigint null references public.orarend_verziok(id) on delete cascade,

    fajlnev          text not null,
    fajl_meret       bigint not null default 0,
    fajl_sha256      text not null default '',
    formatum         text not null default 'ismeretlen',

    statusz          text not null default 'feldolgozva'
                     check (statusz in ('feldolgozva', 'ervenytelen', 'publikalva')),

    sorok_szama      integer not null default 0,
    hibak_szama      integer not null default 0,
    figyelmeztetesek_szama integer not null default 0,

    hibak            jsonb not null default '[]'::jsonb,
    figyelmeztetesek jsonb not null default '[]'::jsonb,
    statisztika      jsonb not null default '{}'::jsonb,

    letrehozta       uuid null,
    created_at       timestamptz not null default now()
);

create index if not exists importok_created_idx on public.importok (created_at desc);
create index if not exists importok_verzio_idx  on public.importok (verzio_id);

-- ─────────────────────────────────────────────────────────────────
-- 3. Órarend sorok verziózása
-- ─────────────────────────────────────────────────────────────────

alter table public.orarendek
    add column if not exists verzio_id bigint null
        references public.orarend_verziok(id) on delete cascade;

-- A csoportonkénti importból származó csoportszám (NULL = az egész osztályé).
alter table public.orarendek
    add column if not exists csoport smallint null;

create index if not exists orarendek_verzio_idx on public.orarendek (verzio_id);
create index if not exists orarendek_aktiv_nap_idx on public.orarendek (aktiv, het_napja);



do $$
declare
    v_legacy_id bigint;
    v_count     bigint;
begin
    select count(*) into v_count from public.orarendek where verzio_id is null;
    if v_count = 0 then
        return;
    end if;

    select id into v_legacy_id
      from public.orarend_verziok
     where nev = 'Örökölt órarend'
     limit 1;

    if v_legacy_id is null then
        insert into public.orarend_verziok (nev, tanev, statusz, published_at, megjegyzes)
        values (
            'Örökölt órarend',
            to_char(now(), 'YYYY'),
            case
                when exists (select 1 from public.orarend_verziok where statusz = 'active')
                    then 'archived'
                else 'active'
            end,
            now(),
            'A verziókezelés bevezetése előtt importált sorok.'
        )
        returning id into v_legacy_id;
    end if;

    update public.orarendek
       set verzio_id = v_legacy_id
     where verzio_id is null;
end
$$;



create or replace function public.ticky_publish_orarend_verzio(p_verzio_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_verzio  public.orarend_verziok%rowtype;
    v_elozo   bigint;
    v_sorok   bigint;
begin
    select * into v_verzio
      from public.orarend_verziok
     where id = p_verzio_id
       for update;

    if not found then
        raise exception 'ISMERETLEN_VERZIO' using errcode = 'P0002';
    end if;

    if v_verzio.statusz = 'active' then
        raise exception 'MAR_AKTIV' using errcode = 'P0001';
    end if;

    select count(*) into v_sorok
      from public.orarendek
     where verzio_id = p_verzio_id;

    if v_sorok = 0 then
        raise exception 'URES_VERZIO' using errcode = 'P0001';
    end if;

    select id into v_elozo
      from public.orarend_verziok
     where statusz = 'active'
     limit 1;

    -- Régi aktív leváltása
    update public.orarendek set aktiv = false where aktiv = true;
    update public.orarend_verziok set statusz = 'archived' where statusz = 'active';

    -- Új verzió élesítése
    update public.orarendek set aktiv = true where verzio_id = p_verzio_id;
    update public.orarend_verziok
       set statusz = 'active',
           published_at = now()
     where id = p_verzio_id;

    update public.importok
       set statusz = 'publikalva'
     where verzio_id = p_verzio_id;

    return jsonb_build_object(
        'ok', true,
        'verzio_id', p_verzio_id,
        'elozo_verzio_id', v_elozo,
        'sorok', v_sorok
    );
end;
$$;

revoke all on function public.ticky_publish_orarend_verzio(bigint) from public, anon, authenticated;



create or replace function public.ticky_delete_orarend_draft(p_verzio_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_statusz text;
    v_sorok   bigint;
begin
    select statusz into v_statusz
      from public.orarend_verziok
     where id = p_verzio_id
       for update;

    if not found then
        raise exception 'ISMERETLEN_VERZIO' using errcode = 'P0002';
    end if;

    if v_statusz <> 'draft' then
        raise exception 'CSAK_DRAFT_TOROLHETO' using errcode = 'P0001';
    end if;

    select count(*) into v_sorok from public.orarendek where verzio_id = p_verzio_id;

    -- A kapcsolt orarendek és importok sorokat a FK ON DELETE CASCADE viszi.
    delete from public.orarend_verziok where id = p_verzio_id;

    return jsonb_build_object('ok', true, 'verzio_id', p_verzio_id, 'torolt_sorok', v_sorok);
end;
$$;

revoke all on function public.ticky_delete_orarend_draft(bigint) from public, anon, authenticated;



alter table public.orarend_verziok enable row level security;
alter table public.importok        enable row level security;

drop policy if exists orarend_verziok_publikus_olvasas on public.orarend_verziok;
create policy orarend_verziok_publikus_olvasas
    on public.orarend_verziok
    for select
    to anon, authenticated
    using (statusz = 'active');


-- ─────────────────────────────────────────────────────────────────

alter table public.orarendek enable row level security;

drop policy if exists orarendek_publikus_olvasas on public.orarendek;
create policy orarendek_publikus_olvasas
    on public.orarendek
    for select
    to anon, authenticated
    using (aktiv = true);
