-- ticky-backend/sql/002_support_uzenetek.sql
--
-- Support üzenetek tárolása.
-- Futtatás: Supabase → SQL Editor → egyszer lefuttatni.
-- A szkript idempotens, újrafuttatható.
--
-- Miért tábla és nem csak email:
-- A kézbesítés (email API) hálózati művelet, tehát hibázhat. Ha az üzenet
-- CSAK emailben létezne, egy lejárt API kulcs vagy egy 500-as válasz
-- nyomtalanul elnyelné a diák bejelentését. Ezért az adatbázis az elsődleges
-- tároló, az email csak értesítés. Ami itt bent van, az nem veszhet el.

-- ─────────────────────────────────────────────────────────────────
-- 1. Üzenettábla
-- ─────────────────────────────────────────────────────────────────

create table if not exists public.support_uzenetek (
    id              bigint generated by default as identity primary key,

    nev             text not null,
    email           text not null,
    kategoria       text not null
                    check (kategoria in ('hiba','kerdes','terem','tanar','osztaly','javaslat','egyeb')),
    uzenet          text not null,

    -- Ügykezelési állapot: az admin állítja.
    statusz         text not null default 'uj'
                    check (statusz in ('uj','folyamatban','lezart')),

    -- Kézbesítési állapot: a rendszer írja, az admin nem.
    -- 'kikapcsolva' = nincs beállítva email szolgáltató, csak tárolunk.
    kezbesites      text not null default 'fuggoben'
                    check (kezbesites in ('fuggoben','elkuldve','sikertelen','kikapcsolva')),
    kezbesites_hiba text null,

    -- Visszaélés visszakövetéséhez elég a hash, a nyers IP-t nem tároljuk.
    ip_hash         text null,
    user_agent      text null,

    created_at      timestamptz not null default now(),
    lezarva_at      timestamptz null
);

-- Az admin lista mindig "legújabb elöl", státusz szerint szűrve.
create index if not exists support_uzenetek_statusz_idx
    on public.support_uzenetek (statusz, created_at desc);

-- Visszaélés-vizsgálathoz: egy IP mennyit küldött az elmúlt napokban.
create index if not exists support_uzenetek_ip_idx
    on public.support_uzenetek (ip_hash, created_at desc);

-- ─────────────────────────────────────────────────────────────────
-- 2. Jogosultság
--
-- A support üzenet magánlevél: benne van a küldő neve és email címe.
-- Publikus szerep SEM olvasni, SEM írni nem tudja. Az írás a szerveroldali
-- service key-jel történik, ami environment változóból jön, és sosem kerül
-- kliensoldali kódba.
-- ─────────────────────────────────────────────────────────────────

alter table public.support_uzenetek enable row level security;

-- Policy önmagában nem elég, a tábla szintű jogot is el kell venni:
-- a PostgREST előbb a GRANT-en bukik el, és az RLS már nem is számít.
revoke all on public.support_uzenetek from anon, authenticated;
revoke all on sequence public.support_uzenetek_id_seq from anon, authenticated;

-- Ellenőrzés (üres listát kell adnia):
--   select grantee, privilege_type from information_schema.role_table_grants
--   where table_name = 'support_uzenetek' and grantee in ('anon','authenticated');
